// app/utils/localization.ts

export type Language = 'th' | 'en';

export const LOCALIZATION: Record<Language, Record<string, string>> = {
  th: {
    'badge-main': 'ถูกต้องตามประมวลกฎหมายแพ่งและพาณิชย์',
    'heading-main': 'เครื่องมือสร้างสัญญาออนไลน์ฟรี',
    'subheading-main': 'สร้างสัญญาเช่าคอนโดมิเนียม พร้อมเงื่อนไขค่าเช่า เงินประกัน และการเข้าพักอย่างครบถ้วนภายในไม่กี่นาที',
    'btn-quick-fill': 'กรอกสัญญาตัวอย่าง',
    'nav-steps-title': 'ขั้นตอนการทำสัญญา',
    'step1-nav-title': 'ข้อมูลคู่สัญญา',
    'step1-nav-desc': 'กรอกชื่อ ที่อยู่ และข้อมูลผู้ลงนาม',
    'step1-nav-title-vehicle-sale': 'ข้อมูลผู้ขายและผู้ซื้อ',
    'step1-nav-desc-vehicle-sale': 'ระบุชื่อ ที่อยู่ และผู้รับมอบอำนาจสำหรับการขายรถยนต์',
    'step1-nav-title-property-sale': 'ข้อมูลผู้ขายและผู้ซื้อ',
    'step1-nav-desc-property-sale': 'ระบุชื่อ ที่อยู่ และผู้รับมอบอำนาจสำหรับอสังหาริมทรัพย์',
    'step1-nav-title-employment': 'ข้อมูลนายจ้างและลูกจ้าง',
    'step1-nav-desc-employment': 'ระบุชื่อ ที่อยู่ และตำแหน่งงานของทั้งสองฝ่าย',
    'step1-nav-title-testament': 'ข้อมูลผู้จัดการและผู้รับมรดก',
    'step1-nav-desc-testament': 'ระบุชื่อผู้ทำพินัยกรรม ผู้จัดการ และผู้รับผลประโยชน์',
    'step2-nav-title': 'รายละเอียดสัญญา',
    'step2-nav-desc': 'กรอกสินทรัพย์ ตำแหน่งงาน หรือพินัยกรรมตามประเภทสัญญา',
    'step2-nav-title-vehicle-sale': 'รายละเอียดรถยนต์',
    'step2-nav-desc-vehicle-sale': 'กรอกรุ่น ปี เลขทะเบียน และราคาขาย',
    'step2-nav-title-property-sale': 'รายละเอียดอสังหาริมทรัพย์',
    'step2-nav-desc-property-sale': 'กรอกรายละเอียดที่ตั้ง เนื้อที่ และราคาขาย',
    'step2-nav-title-employment': 'รายละเอียดงานและค่าตอบแทน',
    'step2-nav-desc-employment': 'ระบุตำแหน่ง เงินเดือน เวลาเริ่มงาน และสวัสดิการ',
    'step2-nav-title-testament': 'รายละเอียดพินัยกรรม',
    'step2-nav-desc-testament': 'ระบุทรัพย์สิน ผู้รับประโยชน์ และพยาน',
    'step3-nav-title': 'เงื่อนไขและวันลงนาม',
    'step3-nav-desc': 'กำหนดวันทำสัญญา เงื่อนไขการส่งมอบหรือชำระเงิน และที่ตั้งสัญญา',
    'step3-nav-title-vehicle-sale': 'การโอนรถ & การชำระเงิน',
    'step3-nav-desc-vehicle-sale': 'กำหนดวันโอนกรรมสิทธิ์ การส่งมอบรถ และวิธีชำระเงิน',
    'step3-nav-title-property-sale': 'การโอนกรรมสิทธิ์ & การชำระเงิน',
    'step3-nav-desc-property-sale': 'กำหนดวันโอนกรรมสิทธิ์ สถานที่โอน และวิธีชำระเงิน',
    'step3-nav-title-employment': 'เงื่อนไขการจ้างงาน',
    'step3-nav-desc-employment': 'กำหนดวันที่เริ่มงาน สถานที่ทำงาน และเงื่อนไขการชำระเงิน',
    'step3-nav-title-testament': 'เงื่อนไขพินัยกรรม',
    'step3-nav-desc-testament': 'กำหนดวันที่ลงนาม พยาน และการแบ่งมรดก',
    'step4-nav-title': 'ทบทวน & ส่งออก',
    'step4-nav-desc': 'ตรวจสอบสัญญา คัดลอก หรือดาวน์โหลด',
    'disclaimer-title': 'ข้อแนะนำทางกฎหมาย:',
    'disclaimer-text': 'สัญญานี้เป็นร่างสัญญามาตรฐานเบื้องต้น ควรตรวจสอบความถูกต้องของเงื่อนไขพิเศษหรือติดต่อทนายความหากเป็นธุรกรรมที่มีมูลค่าสูงมาก',
    'step1-header-title': 'ข้อมูลคู่สัญญา (Parties Information)',
    'step1-header-desc': 'ระบุตัวตนและที่อยู่ของทั้งฝ่ายผู้ให้เช่าและผู้เช่าเพื่อความสมบูรณ์ของกฎหมาย',
    'section-seller': 'ข้อมูลฝ่ายผู้ให้เช่า (Landlord)',
    'section-buyer': 'ข้อมูลฝ่ายผู้เช่า (Tenant)',
    'lbl-name': 'ชื่อบริษัท หรือ ชื่อ-นามสกุล',
    'lbl-address': 'ที่อยู่ตามทะเบียนบ้าน/ที่ตั้งสำนักงาน',
    'lbl-tax-id': 'เลขประจำตัวผู้เสียภาษี / เลขบัตรประชาชน',
    'lbl-signer': 'ชื่อผู้มีอำนาจลงนาม (ถ้ามี)',
    'step2-header-title': 'ข้อมูลยูนิตและสรุปค่าเช่า',
    'step2-header-desc': 'ระบุรายละเอียดยูนิต จำนวน และค่าเช่ารายเดือนทั้งหมด',
    'section-product': 'รายละเอียดยูนิตเช่า',
    'lbl-product-name': 'รายละเอียดยูนิตเช่า',
    'lbl-quantity': 'จำนวน',
    'lbl-unit': 'หน่วยนับ (เช่น ยูนิต, ห้อง)',
    'lbl-unit-price': 'ค่าเช่ารายเดือน',
    'lbl-currency': 'สกุลเงิน',
    'lbl-total-price': 'รวมค่าเช่ารายเดือน (คำนวณอัตโนมัติ)',
    'step3-header-title': 'ข้อกำหนดการเข้าพักและการชำระค่าเช่า',
    'step3-header-desc': 'กำหนดวันเริ่มสัญญา ค่าเช่า เงินประกัน และเบี้ยปรับ',
    'section-delivery': 'เงื่อนไขการเข้าพัก (Move-In Condition)',
    'section-payment': 'เงื่อนไขการชำระค่าเช่า (Rent Payment Terms)',
    'lbl-delivery-deadline': 'วันเริ่มสัญญา',
    'lbl-delivery-method': 'เงื่อนไขการเข้าพัก',
    'opt-del-1': 'ผู้เช่าสามารถเข้าพักได้เมื่อได้รับกุญแจและเอกสารครบถ้วน',
    'opt-del-2': 'เข้าพักตามวันที่นัดหมายหลังจากตรวจสภาพห้อง',
    'opt-del-3': 'เจ้าของมอบกุญแจผ่านตัวแทนหรือผู้ดูแลอาคาร',
    'lbl-payment-method': 'วิธีการชำระค่าเช่า',
    'opt-pay-1': 'ชำระค่าเช่ารายเดือนล่วงหน้าทุกวันที่ 1',
    'opt-pay-2': 'ชำระเงินมัดจำก่อนเข้าพัก และค่าเช่ารายเดือนล่วงหน้าต่อเดือน',
    'lbl-deposit': 'จำนวนเงินประกัน (หากมี)',
    'lbl-penalty': 'อัตราเบี้ยปรับการชำระล่าช้า (ต่อเดือน)',
    'lbl-penalty-hint': 'คำนวณเป็นร้อยละของค่าเช่ารายเดือนที่ค้างชำระต่อเดือน (เช่น 1% - 2%)',
    'lbl-contract-date': 'วันที่ทำสัญญา',
    'lbl-state': 'ทำขึ้น ณ (จังหวัด / อำเภอ)',
    'lbl-country': 'ประเทศที่ใช้บังคับกฎหมาย',
    'step4-header-title': 'สัญญาเช่าเสร็จสมบูรณ์!',
    'step4-header-desc': 'คุณสามารถพรีวิวสัญญา เชื่อมคัดลอก HTML หรือดาวน์โหลดเป็นไฟล์สู่การพิมพ์และลงนามได้ทันที',
    'fmt-btn-preview': 'ดูตัวอย่างสัญญา',
    'fmt-btn-code': 'โค้ด HTML',
    'btn-copy': 'คัดลอกสัญญา',
    'btn-download': 'ดาวน์โหลดไฟล์สัญญา',
    'btn-prev': 'ย้อนกลับ',
    'btn-next': 'ขั้นตอนถัดไป',
    'footer-copy': 'สร้างสรรค์ขึ้นเพื่ออำนวยความสะดวกแก่ผู้ประกอบการไทย',
    'footer-home': 'หน้าแรก',
    'footer-tc': 'คู่มือสัญญา',
    'footer-privacy': 'ช่วยเหลือข้อกฎหมาย',
    'fill-alert-success': 'กรอกข้อมูลสัญญาตัวอย่างเรียบร้อยแล้ว!',
    'validation-alert': 'กรุณากรอกข้อมูลสำคัญที่มีเครื่องหมายดอกจัน (*) ให้ครบถ้วนก่อนเข้าสู่ขั้นถัดไป'
  },
  en: {
    'badge-main': 'Civil & Commercial Standard Contract',
    'heading-main': 'Free Online Contract Generator',
    'subheading-main': 'Generate condominium lease agreements with clear rent, deposit, and move-in terms in minutes.',
    'btn-quick-fill': 'Quick Demo Fill',
    'nav-steps-title': 'AGREEMENT WORKFLOW',
    'step1-nav-title': 'Parties Details',
    'step1-nav-desc': 'Enter names, addresses, and signing parties',
    'step1-nav-title-vehicle-sale': 'Seller and Buyer Details',
    'step1-nav-desc-vehicle-sale': 'Enter seller, buyer, and authorized representative information for the vehicle sale',
    'step1-nav-title-property-sale': 'Seller and Buyer Details',
    'step1-nav-desc-property-sale': 'Enter seller, buyer, and authorized representative information for the property sale',
    'step1-nav-title-employment': 'Employer and Employee Details',
    'step1-nav-desc-employment': 'Enter employer, employee, and job role information',
    'step1-nav-title-testament': 'Testator and Beneficiary Details',
    'step1-nav-desc-testament': 'Enter the testator, executor, and beneficiary details',
    'step2-nav-title': 'Contract Details',
    'step2-nav-desc': 'Enter asset, job, or testament details according to the contract type',
    'step2-nav-title-vehicle-sale': 'Vehicle Details',
    'step2-nav-desc-vehicle-sale': 'Enter make, model, plate, year, and sale price',
    'step2-nav-title-property-sale': 'Property Details',
    'step2-nav-desc-property-sale': 'Enter address, area, floor, and sale price',
    'step2-nav-title-employment': 'Job & Compensation Details',
    'step2-nav-desc-employment': 'Specify position, salary, start date, and benefits',
    'step2-nav-title-testament': 'Will Details',
    'step2-nav-desc-testament': 'Specify assets, beneficiaries, and witnesses',
    'step3-nav-title': 'Contract Dates & Terms',
    'step3-nav-desc': 'Set signature date, delivery/payment terms, and contract location',
    'step3-nav-title-vehicle-sale': 'Vehicle Transfer & Payment',
    'step3-nav-desc-vehicle-sale': 'Set ownership transfer date, delivery method, and payment terms',
    'step3-nav-title-property-sale': 'Ownership Transfer & Payment',
    'step3-nav-desc-property-sale': 'Set transfer date, registration location, and payment terms',
    'step3-nav-title-employment': 'Employment Terms',
    'step3-nav-desc-employment': 'Set start date, work location, and payment terms',
    'step3-nav-title-testament': 'Will Execution Terms',
    'step3-nav-desc-testament': 'Set signing date, witnesses, and inheritance terms',
    'step4-nav-title': 'Review & Export',
    'step4-nav-desc': 'Preview the contract, copy, or download',
    'disclaimer-title': 'Legal Notice:',
    'disclaimer-text': 'This generated contract is a standard template. For high-value transactions or complex commercial deals, please consult a legal professional.',
    'step1-header-title': 'Contracting Parties Details',
    'step1-header-desc': 'Input names and addresses of both landlord and tenant to bind the lease legally.',
    'section-seller': 'Landlord Credentials',
    'section-buyer': 'Tenant Credentials',
    'lbl-name': 'Company Name / Individual Full Name',
    'lbl-address': 'Registered Office Address / Primary Residence',
    'lbl-tax-id': 'Tax ID / ID Card Number',
    'lbl-signer': 'Authorized Representative (If applicable)',
    'step2-header-title': 'Property Specifications & Rent Summary',
    'step2-header-desc': 'List the unit details, quantity, and monthly rent totals.',
    'section-product': 'Condominium Unit for Lease',
    'lbl-product-name': 'Rental Unit Description',
    'lbl-quantity': 'Quantity',
    'lbl-unit': 'Unit (e.g., unit, room)',
    'lbl-unit-price': 'Monthly Rent',
    'lbl-currency': 'Currency',
    'lbl-total-price': 'Total Monthly Rent (Auto-calculates)',
    'step3-header-title': 'Lease Commencement & Payment Terms',
    'step3-header-desc': 'Define the lease start date, rent payment schedule, deposit, and late fees.',
    'section-delivery': 'Occupancy Terms',
    'section-payment': 'Rent Payment Terms',
    'lbl-delivery-deadline': 'Lease Start Date',
    'lbl-delivery-method': 'Move-in / Occupancy Condition',
    'opt-del-1': 'Tenant may occupy after receipt of keys and move-in documents',
    'opt-del-2': 'Tenant moves in on the agreed inspection date',
    'opt-del-3': 'Landlord delivers keys through building management or agent',
    'lbl-payment-method': 'Monthly Payment Structure',
    'opt-pay-1': 'Monthly rent payable in advance on the 1st of each month',
    'opt-pay-2': 'Security deposit paid prior to move-in and monthly rent thereafter',
    'lbl-deposit': 'Security Deposit Amount (If any)',
    'lbl-penalty': 'Late Rent Penalty Rate (Per month)',
    'lbl-penalty-hint': 'Percentage of monthly rent charged for each overdue payment period (e.g. 2% - 5%).',
    'lbl-contract-date': 'Date of Signing',
    'lbl-state': 'Executed At (City / Province)',
    'lbl-country': 'Governing Law Country',
    'step4-header-title': 'Lease Agreement Ready!',
    'step4-header-desc': 'Preview the lease agreement, copy the HTML, or export a printable file.',
    'fmt-btn-preview': 'Rich Contract Preview',
    'fmt-btn-code': 'Raw HTML',
    'btn-copy': 'Copy Contract',
    'btn-download': 'Download Contract File',
    'btn-prev': 'Go Back',
    'btn-next': 'Next Step',
    'footer-copy': 'Designed to simplify corporate operations globally.',
    'footer-home': 'Home',
    'footer-tc': 'User Manuals',
    'footer-privacy': 'Legal Helpdesk',
    'fill-alert-success': 'Sample contract data compiled successfully!',
    'validation-alert': 'Please fill out all marked required fields (*) before continuing.'
  }
};

export const t = (key: string, lang: Language): string =>
  LOCALIZATION[lang][key] || LOCALIZATION.th[key] || '';
